In [1]:
import os

In [2]:
os.chdir('E:\Projects\Vehicle sales forecasting')

In [4]:
os.getcwd()

'E:\\Projects\\Vehicle sales forecasting'

In [5]:
os.listdir()

['items.csv',
 'item_categories.csv',
 'SA.xlsx',
 'sales_train.csv',
 'shops.csv',
 'test.csv']

In [6]:
import pandas as pd

In [20]:
df = pd.DataFrame({"A" : [1,2,3,4],
                  "B" : [10,20,30,40],
                  "C":['A','B','C','D']})

df

A   B  C
0  1  10  A
1  2  20  B
2  3  30  C
3  4  40  D

In [23]:
b = df['C'].value_counts().reset_index()

In [24]:
b

index  C
0     A  1
1     C  1
2     D  1
3     B  1

In [25]:
b['index']

0    A
1    C
2    D
3    B
Name: index, dtype: object

In [33]:
c = pd.DataFrame({'A':[1,2,3],
                 'B':[5,6,7],
                 'E':[1,2,3],
                 'D':[1,2,3],
                 'C':[1,2,3],
                 'F':[1,2,np.nan]})

c

A  B  E  D  C    F
0  1  5  1  1  1  1.0
1  2  6  2  2  2  2.0
2  3  7  3  3  3  NaN

In [34]:
c[b['index']]

A  C  D  B
0  1  1  1  5
1  2  2  2  6
2  3  3  3  7

In [35]:
import numpy as np
mat = c.to_numpy(dtype = float, na_value = np.nan, copy = False)
mat

array([[ 1.,  5.,  1.,  1.,  1.,  1.],
       [ 2.,  6.,  2.,  2.,  2.,  2.],
       [ 3.,  7.,  3.,  3.,  3., nan]])

In [36]:
mat.T

array([[ 1.,  2.,  3.],
       [ 5.,  6.,  7.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2., nan]])

In [40]:
mask = np.isfinite(mat)

In [39]:
for a,b in enumerate(mat):
    print(a)
    print(b)

0
[1. 5. 1. 1. 1. 1.]
1
[2. 6. 2. 2. 2. 2.]
2
[ 3.  7.  3.  3.  3. nan]


In [41]:
mask

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False]])

In [43]:
mask[0]

array([ True,  True,  True,  True,  True,  True])

In [44]:
mask[2]

array([ True,  True,  True,  True,  True, False])

In [46]:
mask[0]&mask[2]

array([ True,  True,  True,  True,  True, False])

In [53]:
a = np.array([1,2,3,4,5,6])
b = np.array([10,20,30,40,50,60])
b[np.array([True,True,False,True,False,True])]-a[np.array([True,True,False,True,False,True])]

array([ 9, 18, 36, 54])

In [55]:
c.columns

Index(['A', 'B', 'E', 'D', 'C', 'F'], dtype='object')

In [56]:
dfa = pd.DataFrame({'100-1':[1,2,3],
                   '101-1':[1,2,3],
                   '102-1':[1,2,3],
                   '103-1':[1,2,3]})
dfa

100-1  101-1  102-1  103-1
0      1      1      1      1
1      2      2      2      2
2      3      3      3      3

In [57]:
names = dfa.columns
names

Index(['100-1', '101-1', '102-1', '103-1'], dtype='object')

In [59]:
names.str.split(pat = '-', expand = True).to_frame()

0  1
100 1  100  1
101 1  101  1
102 1  102  1
103 1  103  1

In [60]:
names = names.str.split(pat = '-', expand = True).to_frame()
names = names[0] + '-' + names[1]
names

100  1    100-1
101  1    101-1
102  1    102-1
103  1    103-1
dtype: object

In [61]:
dfa

100-1  101-1  102-1  103-1
0      1      1      1      1
1      2      2      2      2
2      3      3      3      3

In [62]:
dfa.rename_axis('SPN-FMI', axis = 'index')

100-1  101-1  102-1  103-1
SPN-FMI                            
0            1      1      1      1
1            2      2      2      2
2            3      3      3      3

In [63]:
dfa.rename_axis('SPN-FMI', axis = 'columns')

SPN-FMI  100-1  101-1  102-1  103-1
0            1      1      1      1
1            2      2      2      2
2            3      3      3      3

In [64]:
df1 = pd.DataFrame({"A":[1, 5, 3, 4, 2], 
                    "B":[3, 2, 4, 3, 4], 
                    "C":[2, 2, 7, 3, 4], 
                    "D":[4, 3, 6, 12, 7]}) 

df1

A  B  C   D
0  1  3  2   4
1  5  2  2   3
2  3  4  7   6
3  4  3  3  12
4  2  4  4   7

In [65]:
df1.reindex(columns = ['D','C','B','A'])

D  C  B  A
0   4  2  3  1
1   3  2  2  5
2   6  7  4  3
3  12  3  3  4
4   7  4  4  2

In [67]:
df1.style.background_gradient().to_excel(r'E:\Check the colormap.xlsx')